# Generated by Django 6.0.2 on 2026-03-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutme",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
        migrations.AlterField(
            model_name="aboutme",
            name="profile_image_url",
            field=models.URLField(
                blank=True,
                help_text="CDN URL for profile image (used if no image is uploaded)",
            ),
        ),
    ]
