# Generated by Django 6.0.2 on 2026-05-20 02:21

from django.db import migrations, models


def rename_thumbnail_paths(apps, schema_editor):
    """Update existing Blog thumbnail_img paths from images/ to postimages/."""
    Blog = apps.get_model("home", "Blog")
    for blog in Blog.objects.filter(thumbnail_img__startswith="images/"):
        blog.thumbnail_img = blog.thumbnail_img.name.replace(
            "images/", "postimages/", 1
        )
        blog.save(update_fields=["thumbnail_img"])


def reverse_rename(apps, schema_editor):
    """Reverse: rename postimages/ back to images/."""
    Blog = apps.get_model("home", "Blog")
    for blog in Blog.objects.filter(thumbnail_img__startswith="postimages/"):
        blog.thumbnail_img = blog.thumbnail_img.name.replace(
            "postimages/", "images/", 1
        )
        blog.save(update_fields=["thumbnail_img"])


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_alter_aboutme_resume_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="thumbnail_img",
            field=models.ImageField(blank=True, null=True, upload_to="postimages/"),
        ),
        migrations.RunPython(rename_thumbnail_paths, reverse_rename),
    ]
