# Generated by Django 6.0.2 on 2026-05-20 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_experience_url_worktype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="position",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExperienceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=200)),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("on-site", "On-site"),
                            ("hybrid", "Hybrid"),
                            ("remote", "Remote"),
                        ],
                        default="on-site",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Leave blank if current", null=True
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Check if this is your current position",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Each line becomes a bullet point."
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower numbers first)"
                    ),
                ),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="home.experience",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experience Role",
                "verbose_name_plural": "Experience Roles",
                "ordering": ["order", "-start_date"],
            },
        ),
    ]
