# Generated by Django 6.0.2 on 2026-05-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("home", "0012_experience_roles"),
    ]

    operations = [  # noqa: RUF012
        migrations.AddField(
            model_name="experiencerole",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full-time", "Full-time"),
                    ("part-time", "Part-time"),
                    ("self-employed", "Self-employed"),
                    ("freelance", "Freelance"),
                    ("contract", "Contract"),
                    ("internship", "Internship"),
                    ("apprenticeship", "Apprenticeship"),
                    ("seasonal", "Seasonal"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
    ]
