# Generated by Django 6.0.2 on 2026-05-26 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_experience_company_logo_experience_company_logo_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="experiencerole",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "Experience Role",
                "verbose_name_plural": "Experience Roles",
            },
        ),
        migrations.RemoveField(
            model_name="experiencerole",
            name="order",
        ),
    ]
