# Generated by Django 6.0.2 on 2026-05-28 11:36

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_experiencerole_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A friendly name or description for the file.",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=home.models.get_shared_storage, upload_to=""
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Shared File",
                "verbose_name_plural": "Shared Files",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
