# Generated by Django 6.0.2 on 2026-06-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_alter_blog_meta_alter_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="When the project was finished. Leave blank if ongoing.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="is_current",
            field=models.BooleanField(
                default=False, help_text="Check if this project is still in progress."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="When the project was started.", null=True
            ),
        ),
    ]
