# Generated by Django 6.0.2 on 2026-07-26 20:01
#
# Project images used to live in two places: a single thumbnail on Project
# plus a ProjectImage gallery. This merges them into one ordered list — the
# old thumbnail becomes the first ProjectImage row (the cover) — and then
# drops the now-redundant Project fields.

from django.db import migrations


def thumbnail_to_gallery(apps, schema_editor):
    """Move each project's thumbnail into the gallery as slide #1."""
    Project = apps.get_model("home", "Project")
    ProjectImage = apps.get_model("home", "ProjectImage")

    for project in Project.objects.all():
        thumb_file = project.thumbnail_img.name if project.thumbnail_img else ""
        thumb_url = project.thumbnail_url or ""
        if not thumb_file and not thumb_url:
            continue

        existing = list(ProjectImage.objects.filter(project=project))

        # Skip if the thumbnail is already in the gallery (e.g. re-run)
        already_there = any(
            (thumb_file and image.image == thumb_file)
            or (thumb_url and image.image_url == thumb_url)
            for image in existing
        )
        if already_there:
            continue

        # Make room at the top so the cover keeps rendering first
        for image in existing:
            image.order = (image.order or 0) + 1
            image.save(update_fields=["order"])

        ProjectImage.objects.create(
            project=project,
            image=thumb_file,
            image_url=thumb_url,
            caption="",
            order=0,
        )


def gallery_to_thumbnail(apps, schema_editor):
    """Reverse: promote the first gallery slide back onto the project."""
    Project = apps.get_model("home", "Project")
    ProjectImage = apps.get_model("home", "ProjectImage")

    for project in Project.objects.all():
        first = (
            ProjectImage.objects.filter(project=project).order_by("order", "id").first()
        )
        if not first:
            continue
        project.thumbnail_img = first.image.name if first.image else ""
        project.thumbnail_url = first.image_url or ""
        project.save(update_fields=["thumbnail_img", "thumbnail_url"])
        first.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_projectimage"),
    ]

    operations = [
        migrations.RunPython(thumbnail_to_gallery, gallery_to_thumbnail),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail_img",
        ),
        migrations.RemoveField(
            model_name="project",
            name="thumbnail_url",
        ),
    ]
