# Generated by Django 6.0.2 on 2026-07-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [  # noqa: RUF012
        ("home", "0024_merge_project_thumbnail_into_gallery"),
    ]

    operations = [  # noqa: RUF012
        migrations.AlterField(
            model_name="projectimage",
            name="order",
            field=models.IntegerField(
                default=0,
                help_text="Lower numbers first. Leave at 0 to append after the existing images.",
            ),
        ),
    ]
