# Generated by Django 6.0.2 on 2026-07-28 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_feedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
