"""Build the JavaScript snippet catalog consumed by the admin tools picker.

Usage
-----
    python manage.py build_tools_catalog          # build catalog to static/js/generated/
    python manage.py build_tools_catalog --check   # lint every snippet, CSS coverage, exit 1 on error

The catalog is a JS file that assigns a list of snippet objects to
``window.__TK_CATALOG__``.  The admin picker reads it and renders a grouped,
searchable insert panel above each CKEditor instance.
"""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

from home.content_tools import (
    CATALOG_PATH,
    check_all,
    check_css_coverage,
    check_preview_coverage,
    load_all,
)


class Command(BaseCommand):
    help = "Build or validate the CKEditor Content Toolkit snippet catalog."

    def add_arguments(self, parser):
        parser.add_argument(
            "--check",
            action="store_true",
            help="Validate every snippet; do not write the catalog file.",
        )

    def handle(self, *args, **options):
        snippets = load_all()
        if not snippets:
            raise CommandError(
                "No snippets found — is the tools/snippets/ directory present?"
            )

        if options["check"]:
            self._check(snippets)
        else:
            self._build(snippets)

    # ── build ───────────────────────────────────────────────────────────

    def _build(self, snippets):
        out = Path(settings.BASE_DIR) / CATALOG_PATH
        out.parent.mkdir(parents=True, exist_ok=True)

        entries = json.dumps(
            [s.as_dict() for s in snippets],
            ensure_ascii=False,
            indent=2,
        )

        header = textwrap.dedent("""\
            /* ─────────────────────────────────────────────────────────────
               AUTO-GENERATED by `manage.py build_tools_catalog`.
               Do NOT edit by hand — change the snippet source file instead
               and re-run the command.
               ───────────────────────────────────────────────────────────── */
        """)

        out.write_text(
            f"{header}window.__TK_CATALOG__ = {entries};\n",
            encoding="utf-8",
        )

        self.stdout.write(
            self.style.SUCCESS(
                f"Wrote {len(snippets)} snippet(s) → {CATALOG_PATH}"
            )
        )

    # ── check ───────────────────────────────────────────────────────────

    def _check(self, snippets):
        ok = True

        # 1. Per-snippet structural checks
        failures = check_all()
        for filename, problems in sorted(failures.items()):
            ok = False
            self.stderr.write(self.style.ERROR(f"\n✗ {filename}"))
            for problem in problems:
                self.stderr.write(f"  · {problem}")

        # 2. CSS coverage
        css_problems = check_css_coverage(snippets)
        for problem in css_problems:
            ok = False
            self.stderr.write(self.style.ERROR(f"  CSS: {problem}"))

        # 3. Preview gallery coverage
        preview_problems = check_preview_coverage(snippets)
        for problem in preview_problems:
            ok = False
            self.stderr.write(self.style.WARNING(f"  Preview: {problem}"))

        if ok:
            self.stdout.write(
                self.style.SUCCESS(
                    f"All {len(snippets)} snippet(s) passed validation."
                )
            )
        else:
            raise CommandError("Snippet validation failed — see errors above.")
